name: Model Training CICD
permissions:
  id-token: write
  contents: write

on: push  # Runs workflow when you push changes

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Debug File Structure  # ✅ Check if requirements.txt exists
        run: |
          echo "Current directory:"
          pwd
          echo "List of files:"
          ls -R

      - name: Install dependencies  # ✅ Ensure requirements.txt path is correct
        run: pip install -r requirements.txt  # Change path if inside a folder

      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python train_model.py  # ✅ Run your model training script
          
          echo "RF and LR Model Score" > report.md
          cat scores.txt

          echo "Confusion Matrix & Feature Importance" > report1.md
          echo '|[](./ConfusionMatrix.png "ConfusionMatrix")' >> report1.md
          echo '|[](./FeatureImportance.png "FeatureImportance")' >> report1.md

          cat report.md report1.md >> combined_file.md
          cml comment create combined_file.md

          git add .github/workflows/cicd.yml
          git commit -m "Updated CICD workflow with debugging"
          git push origin main



