name: Model Training CICD
permissions:
  id-token: write
  contents: write

on: push

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up CML
        uses: iterative/setup-cml@v1

      - name: Install dependencies
        run: pip install -r requirements.txt  # Change if inside a folder

      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "RF and LR Model Score" > report.md
          cat scores.txt

          echo "Confusion Matrix & Feature Importance" > report1.md
          echo '|[](./ConfusionMatrix.png "ConfusionMatrix")' >> report1.md
          echo '|[](./FeatureImportance.png "FeatureImportance")' >> report1.md

          cat report.md report1.md >> combined_file.md
          cml comment create combined_file.md

